pipeline:
  build:
    image: node:10-alpine
    commands:
      - "apk --no-cache add --virtual build-dependencies git python make gcc g++ musl-dev"
      - "npm install"
      - "npm run build"
      - "apk del build-dependencies"
    when:
      branch:
        - dev
      event:
        - push
        - tag
  notify-build:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    when:
      branch:
        - dev
      status:
        - success
        - failure
      event:
        - push
        - tag
  publish:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    registry: dev.enecuum.com:2087
    repo: dev.enecuum.com:2087/site/frontend
    tags: latest
    when:
      branch:
        - dev
      status:
        - success
      event:
        - push
        - tag
  deploy-dev:
    image: peloton/drone-rancher
    url: https://dev.enecuum.com:2096
    secrets:
      - source: rancher_access_key
        target: PLUGIN_ACCESS_KEY
      - source: rancher_secret_key
        target: PLUGIN_SECRET_KEY
    docker_image: dev.enecuum.com:2087/site/frontend:latest
    service: site/frontend-dev
    confirm: true
    timeout: 240
    when:
      branch:
        - dev
      status:
        - success
      event:
        - push
        - tag
  deploy-prod:
    image: peloton/drone-rancher
    url: https://dev.enecuum.com:2096
    secrets:
      - source: rancher_access_key
        target: PLUGIN_ACCESS_KEY
      - source: rancher_secret_key
        target: PLUGIN_SECRET_KEY
    docker_image: dev.enecuum.com:2087/site/frontend:latest
    service: site/frontend-prod
    confirm: true
    timeout: 240
    when:
      branch:
        - master
      status:
        - success
      event:
        - push
        - tag
  notify-deploy-dev:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    message: \u2705 ${DRONE_REPO}:`${DRONE_COMMIT_BRANCH}` ${DRONE_BUILD_NUMBER} deployment successful
    when:
      branch:
        - dev
      status:
        - success
      event:
        - push
        - tag
  notify-deploy-prod:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    message: \u2705 ${DRONE_REPO}:`${DRONE_COMMIT_BRANCH}` ${DRONE_BUILD_NUMBER} deployment successful
    when:
      branch:
        - master
      status:
        - success
      event:
        - push
        - tag
  notify-pr:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    message: \u2757 PR ${DRONE_REPO_LINK}/pull/${DRONE_PULL_REQUEST}
    when:
      branch: master
      event: pull_request
